name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # If you have a build step, run it here. If not, skip directly to deploy.

      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          build_dir: .
